import { auth } from "@/auth";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

const session = await auth();
if (!session || session.user.role !== "admin") redirect("/");
  return <>{children}</>;
}
